sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 4582872
  alioss:
    access-key-id: LTAI5t8i6czhWUFzi5RqQN9L
    access-key-secret: Uq0i4UKI28lui7q3OtVNvaG8y88amx
    bucket-name: sky-buck
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    port: 6379
    host: 192.168.160.129
    database: 0